// seed/walletSeedData.js — All mock Sri Lankan driver data
// ─────────────────────────────────────────────────────────

const Y = new Date().getFullYear();

const mockDrivers = [
  // ═══════════════════════════════════════════════════════
  // DRIVER 1: Single vehicle, all valid documents
  // ═══════════════════════════════════════════════════════
  {
    driver: {
      nic:           '199012345678',
      licenseNumber: 'B1234567',
      fullName:      'M.A. Shashimantha',
      bloodGroup:    'B+',
      dateOfBirth:   new Date('1990-05-15'),
      address:       'No 15, Main Street, Dambulla',
      phoneNumber:   '0711234567',
      email:         'shashi@efinesl.lk',
      photo:         'https://placeholder.com/driver-photo.png',
      drivingLicense: {
        licenseNo:        'B1234567',
        issueDate:        new Date('2015-05-15'),
        expiryDate:       new Date('2025-05-15'),
        vehicleClasses:   ['B', 'B1'],
        issuingAuthority: 'Department of Motor Traffic',
        restrictions:     'None',
        status:           'VALID',
      },
    },
    vehicles: [
      {
        registrationNo: 'NCLD5469',
        make:           'MITSUBISHI',
        model:          'GBD-U61T',
        yearOfMfg:      2005,
        vehicleClass:   'MOTOR LORRY',
        chassisNo:      'U61T1010823',
        engineNo:       '3G83-112953',
        fuelType:       'Petrol',
        color:          'White',
        seatingCapacity: 2,
        tareWeight:     800,

        // ── Emission — EXACT values from reference Image 1 ──
        emissionCertificate: {
          serialNo:      'LE 010653872',
          systemNo:      'E 20883872',
          dateOfIssue:   new Date('2020-05-13'),
          validTill:     new Date('2026-05-13'),   // future — VALID
          testCentre:    'Dambulla',
          inspector:     'sankaTD',
          instrumentNo:  'AS091152',
          lane:          1,
          testFee:       1480.00,
          testStartTime: '14:51',
          testEndTime:   '14:53',
          odometer:      125074,
          referenceNo:   'CER27-00225026',
          readings: {
            idle: {
              rpm: 1671, hc: 159, co: 0.37, o2: 9.26, co2: 7.17,
            },
            rpm2500: {
              rpm: 2598, hc: 163, co: 0.35, o2: 10.82, co2: 6.82,
            },
            oilTemp: 'N/A',
          },
          standards:    { hc: 1000, co: 3.00 },
          overallStatus: 'PASS',
          issuingOffice: 'Dambulla Emission Test Centre',
          qrCodeData:    'LE010653872|NCLD5469|PASS|2026-05-13',
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },

        // ── Insurance — EXACT values from reference Image 2 ─
        insuranceCertificate: {
          certificateType:    'VIP',
          policyNo:           'THD001BTA0004407',
          insuredName:        'M.A. Shashimantha',
          insuredAddress:     'No 15, Main Street, Dambulla',
          insurer:            'CEYLINCO GENERAL INSURANCE LTD',
          insurerAddress:     '69, JANADHIPATHI MAWATHA, COLOMBO 01',
          periodOfCoverStart: new Date('2025-01-01'),
          periodOfCoverEnd:   new Date('2025-12-31'),  // active in 2025
          coverageType:       'Third Party',
          premiumAmount:      25000.00,
          status:             'ACTIVE',
          vehicleNo:          'NCLD5469',
          make:               'MITSUBISHI',
          model:              'GBD-U61T',
          engineNo:           'L15B61124008',
          chassisNo:          'MRHRW2859JP067191',
          seatingCapacity:    2,
          issuingBranch:      'Colombo Main Branch',
          agentName:          'Direct',
        },

        revenueLicense: {
          licenseNo:        'RL-2024-NCLD5469',
          issueDate:        new Date('2024-01-01'),
          expiryDate:       new Date('2025-12-31'),  // valid
          issuingAuthority: 'North Central Province Revenue',
          annualFee:        12500.00,
          status:           'VALID',
        },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // DRIVER 2: Three vehicles, mixed document statuses
  // ═══════════════════════════════════════════════════════
  {
    driver: {
      nic:           '198756789012',
      licenseNumber: 'A9876543',
      fullName:      'K.P. Jayawardena',
      bloodGroup:    'O+',
      dateOfBirth:   new Date('1987-08-20'),
      address:       '22, Kandy Road, Kaduwela, Colombo',
      phoneNumber:   '0772345678',
      email:         'jayawardena@efinesl.lk',
      drivingLicense: {
        licenseNo:        'A9876543',
        issueDate:        new Date('2010-08-20'),
        expiryDate:       new Date(`${Y + 3}-08-20`),
        vehicleClasses:   ['A', 'B', 'C1'],
        issuingAuthority: 'Department of Motor Traffic',
        restrictions:     'None',
        status:           'VALID',
      },
    },
    vehicles: [
      // Vehicle 1: WP CAB 1234 — All valid
      {
        registrationNo: 'WP CAB 1234',
        make:           'TOYOTA',
        model:          'PREMIO',
        yearOfMfg:      2015,
        vehicleClass:   'MOTOR CAR',
        chassisNo:      'NZT2601234567',
        engineNo:       '1NZ456789',
        fuelType:       'Petrol',
        color:          'White',
        seatingCapacity: 5,
        tareWeight:     1200,
        emissionCertificate: {
          serialNo:      'LE 09988776',
          systemNo:      'E 55443322',
          dateOfIssue:   new Date(`${Y}-01-10`),
          validTill:     new Date(`${Y + 1}-01-09`),
          testCentre:    'Ratmalana',
          inspector:     'kamalR',
          instrumentNo:  'AS223344',
          lane:          2,
          testFee:       1500.00,
          testStartTime: '09:00',
          testEndTime:   '09:05',
          odometer:      78000,
          referenceNo:   `CER15-${Y}88776`,
          readings: {
            idle:    { rpm: 820, hc: 48, co: 0.10, o2: 12.00, co2: 8.20 },
            rpm2500: { rpm: 2510, hc: 55, co: 0.14, o2: 11.80, co2: 8.60 },
            oilTemp: '88C',
          },
          standards:     { hc: 1000, co: 3.00 },
          overallStatus: 'PASS',
          issuingOffice: 'Ratmalana Branch',
          qrCodeData:    `LE09988776|WPCAB1234|PASS|${Y + 1}-01-09`,
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },
        insuranceCertificate: {
          certificateType:    'COMPREHENSIVE',
          policyNo:           'AIA987654321',
          insuredName:        'K.P. Jayawardena',
          insuredAddress:     '22, Kandy Road, Kaduwela, Colombo',
          insurer:            'AIA INSURANCE',
          insurerAddress:     'AIA Tower, Colombo 03',
          periodOfCoverStart: new Date(`${Y}-01-01`),
          periodOfCoverEnd:   new Date(`${Y + 1}-12-31`),
          coverageType:       'Comprehensive',
          premiumAmount:      85000.00,
          status:             'ACTIVE',
          vehicleNo:          'WP CAB 1234',
          make:               'TOYOTA',
          model:              'PREMIO',
          engineNo:           '1NZ456789',
          chassisNo:          'NZT2601234567',
          seatingCapacity:    5,
          issuingBranch:      'Colombo HQ',
          agentName:          'Direct',
        },
        revenueLicense: {
          licenseNo:        `REV-${Y}-WPCAB1234`,
          issueDate:        new Date(`${Y}-01-01`),
          expiryDate:       new Date(`${Y + 1}-12-31`),
          issuingAuthority: 'Western Province Revenue',
          annualFee:        4500.00,
          status:           'VALID',
        },
      },

      // Vehicle 2: WP KJ 5678 — Motorcycle, all valid
      {
        registrationNo: 'WP KJ 5678',
        make:           'HONDA',
        model:          'BEAT',
        yearOfMfg:      2018,
        vehicleClass:   'MOTOR CYCLE',
        chassisNo:      'JF52123456',
        engineNo:       'JF52E987654',
        fuelType:       'Petrol',
        color:          'Blue',
        seatingCapacity: 2,
        tareWeight:     105,
        emissionCertificate: {
          serialNo:      'CLE 334455',
          dateOfIssue:   new Date(`${Y}-03-01`),
          validTill:     new Date(`${Y + 1}-03-01`),
          testCentre:    'Narahenpita',
          inspector:     'nimalP',
          instrumentNo:  'BIKE-001',
          lane:          1,
          testFee:       450.00,
          testStartTime: '10:00',
          testEndTime:   '10:03',
          odometer:      24000,
          referenceNo:   `CER08-${Y}334455`,
          readings: {
            idle:    { rpm: 1400, hc: 80, co: 0.60, o2: 11.00, co2: 6.50 },
            rpm2500: { rpm: 2505, hc: 95, co: 0.72, o2: 10.50, co2: 7.00 },
            oilTemp: 'N/A',
          },
          standards:     { hc: 2000, co: 4.50 },
          overallStatus: 'PASS',
          issuingOffice: 'Narahenpita Branch',
          qrCodeData:    `CLE334455|WPKJ5678|PASS|${Y + 1}-03-01`,
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },
        insuranceCertificate: {
          certificateType:    'THIRD_PARTY',
          policyNo:           'LOLC-TP-112233',
          insuredName:        'K.P. Jayawardena',
          insuredAddress:     '22, Kandy Road, Kaduwela, Colombo',
          insurer:            'LOLC INSURANCE',
          insurerAddress:     'LOLC Tower, Colombo 02',
          periodOfCoverStart: new Date(`${Y}-02-15`),
          periodOfCoverEnd:   new Date(`${Y + 1}-02-14`),
          coverageType:       'Third Party',
          premiumAmount:      3800.00,
          status:             'ACTIVE',
          vehicleNo:          'WP KJ 5678',
          make:               'HONDA',
          model:              'BEAT',
          engineNo:           'JF52E987654',
          chassisNo:          'JF52123456',
          seatingCapacity:    2,
          issuingBranch:      'Colombo North',
          agentName:          'Direct',
        },
        revenueLicense: {
          licenseNo:        `REV-${Y}-WPKJ5678`,
          issueDate:        new Date(`${Y}-02-01`),
          expiryDate:       new Date(`${Y + 1}-01-31`),
          issuingAuthority: 'Western Province Revenue',
          annualFee:        1800.00,
          status:           'VALID',
        },
      },

      // Vehicle 3: CP PA 9012 — Emission FAIL, insurance & revenue EXPIRED
      {
        registrationNo: 'CP PA 9012',
        make:           'TATA',
        model:          'SUPER ACE',
        yearOfMfg:      2012,
        vehicleClass:   'GOODS VEHICLE',
        chassisNo:      'MAT456789012',
        engineNo:       'DICOR1122334',
        fuelType:       'Diesel',
        color:          'White',
        seatingCapacity: 2,
        tareWeight:     1400,
        emissionCertificate: {
          serialNo:      'LE 556677',
          dateOfIssue:   new Date(`${Y - 1}-06-15`),
          validTill:     new Date(`${Y}-06-14`),
          testCentre:    'Kandy',
          inspector:     'sunilK',
          instrumentNo:  'KAN-002',
          lane:          2,
          testFee:       1500.00,
          testStartTime: '11:00',
          testEndTime:   '11:06',
          odometer:      186000,
          referenceNo:   `CER11-${Y - 1}556677`,
          readings: {
            // Failing values (over standard limits)
            idle:    { rpm: 950, hc: 1450, co: 4.20, o2: 7.10, co2: 5.20 },
            rpm2500: { rpm: 2485, hc: 1620, co: 5.10, o2: 6.80, co2: 4.90 },
            oilTemp: 'N/A',
          },
          standards:     { hc: 1000, co: 3.00 },
          overallStatus: 'FAIL',
          issuingOffice: 'Kandy Branch',
          qrCodeData:    `LE556677|CPPA9012|FAIL|${Y}-06-14`,
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },
        insuranceCertificate: {
          certificateType:    'COMPREHENSIVE',
          policyNo:           'PI-EXP-2023-456',
          insuredName:        'K.P. Jayawardena',
          insuredAddress:     '22, Kandy Road, Kaduwela, Colombo',
          insurer:            'PEOPLES INSURANCE',
          insurerAddress:     'Peoples Insurance Tower, Colombo 01',
          periodOfCoverStart: new Date('2023-01-01'),
          periodOfCoverEnd:   new Date('2023-12-31'),
          coverageType:       'Comprehensive',
          premiumAmount:      55000.00,
          status:             'EXPIRED',
          vehicleNo:          'CP PA 9012',
          make:               'TATA',
          model:              'SUPER ACE',
          engineNo:           'DICOR1122334',
          chassisNo:          'MAT456789012',
          seatingCapacity:    2,
          issuingBranch:      'Kandy',
          agentName:          'Direct',
        },
        revenueLicense: {
          licenseNo:        'REV-2023-CPPA9012',
          issueDate:        new Date('2023-01-01'),
          expiryDate:       new Date('2023-12-31'),
          issuingAuthority: 'Central Province Revenue',
          annualFee:        6500.00,
          status:           'EXPIRED',
        },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // DRIVER 3: Suspended license, one vehicle
  // ═══════════════════════════════════════════════════════
  {
    driver: {
      nic:           '200034567890',
      licenseNumber: 'C5678901',
      fullName:      'R.M. Perera',
      bloodGroup:    'A+',
      dateOfBirth:   new Date('2000-11-11'),
      address:       '45, Marine Drive, Matara',
      phoneNumber:   '0703456789',
      email:         'perera@efinesl.lk',
      drivingLicense: {
        licenseNo:        'C5678901',
        issueDate:        new Date('2021-01-10'),
        expiryDate:       new Date(`${Y + 5}-01-10`),
        vehicleClasses:   ['B'],
        issuingAuthority: 'Department of Motor Traffic',
        restrictions:     'Corrective Lenses Required',
        status:           'SUSPENDED',   // ← SUSPENDED
      },
    },
    vehicles: [
      {
        registrationNo: 'SP AB 4321',
        make:           'SUZUKI',
        model:          'ALTO',
        yearOfMfg:      2019,
        vehicleClass:   'MOTOR CAR',
        chassisNo:      'MA34321SZK',
        engineNo:       'F8D9876LK',
        fuelType:       'Petrol',
        color:          'Red',
        seatingCapacity: 4,
        tareWeight:     740,
        emissionCertificate: {
          serialNo:      'LE 112233',
          dateOfIssue:   new Date(`${Y - 1}-06-01`),
          validTill:     new Date(`${Y - 1}-11-30`),  // EXPIRED — passed PASS but date gone
          testCentre:    'Galle',
          inspector:     'amalS',
          instrumentNo:  'GAL-003',
          lane:          1,
          testFee:       1200.00,
          testStartTime: '08:30',
          testEndTime:   '08:34',
          odometer:      31000,
          referenceNo:   `CER09-${Y - 1}112233`,
          readings: {
            idle:    { rpm: 850, hc: 55, co: 0.12, o2: 12.50, co2: 8.00 },
            rpm2500: { rpm: 2520, hc: 62, co: 0.18, o2: 12.00, co2: 8.40 },
            oilTemp: '85C',
          },
          standards:     { hc: 1000, co: 3.00 },
          overallStatus: 'PASS',           // PASS — but date EXPIRED
          issuingOffice: 'Galle Branch',
          qrCodeData:    `LE112233|SPAB4321|PASS|${Y - 1}-11-30`,
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },
        insuranceCertificate: {
          certificateType:    'COMPREHENSIVE',
          policyNo:           'UA-998877-2025',
          insuredName:        'R.M. Perera',
          insuredAddress:     '45, Marine Drive, Matara',
          insurer:            'UNION ASSURANCE',
          insurerAddress:     'Union Assurance Bldg, Colombo 01',
          periodOfCoverStart: new Date(`${Y}-01-01`),
          periodOfCoverEnd:   new Date(`${Y + 1}-12-31`),
          coverageType:       'Comprehensive',
          premiumAmount:      38000.00,
          status:             'ACTIVE',
          vehicleNo:          'SP AB 4321',
          make:               'SUZUKI',
          model:              'ALTO',
          engineNo:           'F8D9876LK',
          chassisNo:          'MA34321SZK',
          seatingCapacity:    4,
          issuingBranch:      'Matara',
          agentName:          'Direct',
        },
        revenueLicense: {
          licenseNo:        `REV-${Y}-SPAB4321`,
          issueDate:        new Date(`${Y}-01-01`),
          expiryDate:       new Date(`${Y + 1}-12-31`),
          issuingAuthority: 'Southern Province Revenue',
          annualFee:        3200.00,
          status:           'VALID',
        },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // DRIVER 4: All documents expired
  // ═══════════════════════════════════════════════════════
  {
    driver: {
      nic:           '197890123456',
      licenseNumber: 'D2345678',
      fullName:      'A.H. Fernando',
      bloodGroup:    'AB-',
      dateOfBirth:   new Date('1978-04-05'),
      address:       '7, Main Street, Kurunegala',
      phoneNumber:   '0374567890',
      email:         'fernando@efinesl.lk',
      drivingLicense: {
        licenseNo:        'D2345678',
        issueDate:        new Date('2000-04-05'),
        expiryDate:       new Date('2022-04-05'),   // EXPIRED
        vehicleClasses:   ['A', 'B', 'G'],
        issuingAuthority: 'Department of Motor Traffic',
        restrictions:     'None',
        status:           'EXPIRED',
      },
    },
    vehicles: [
      {
        registrationNo: 'NW GH 7890',
        make:           'BAJAJ',
        model:          'THREE WHEELER',
        yearOfMfg:      2010,
        vehicleClass:   'THREE WHEELER',
        chassisNo:      'MD27890BJAJ',
        engineNo:       'DZ1234NW',
        fuelType:       'Petrol',
        color:          'Yellow',
        seatingCapacity: 3,
        tareWeight:     350,
        emissionCertificate: {
          serialNo:      'LE 99999',
          dateOfIssue:   new Date('2022-06-15'),
          validTill:     new Date('2023-06-14'), // EXPIRED
          testCentre:    'Kurunegala',
          inspector:     'bandaK',
          instrumentNo:  'KUR-005',
          lane:          1,
          testFee:       600.00,
          testStartTime: '13:00',
          testEndTime:   '13:04',
          odometer:      280000,
          referenceNo:   'CER22-2022099999',
          readings: {
            idle:    { rpm: 1200, hc: 350, co: 1.10, o2: 10.00, co2: 7.00 },
            rpm2500: { rpm: 2490, hc: 390, co: 1.30, o2: 9.80, co2: 7.40 },
            oilTemp: 'N/A',
          },
          standards:     { hc: 2000, co: 4.50 },
          overallStatus: 'PASS',           // Passed test but now EXPIRED date
          issuingOffice: 'Kurunegala Branch',
          qrCodeData:    'LE99999|NWGH7890|PASS|2023-06-14',
          issuingCompany:'LAUGFS ECO SRI LIMITED',
        },
        insuranceCertificate: {
          certificateType:    'THIRD_PARTY',
          policyNo:           'ALZ-TP-EXP-2022',
          insuredName:        'A.H. Fernando',
          insuredAddress:     '7, Main Street, Kurunegala',
          insurer:            'ALLIANZ INSURANCE',
          insurerAddress:     'Allianz Insurance, Colombo 03',
          periodOfCoverStart: new Date('2022-01-01'),
          periodOfCoverEnd:   new Date('2022-12-31'),  // EXPIRED
          coverageType:       'Third Party',
          premiumAmount:      4200.00,
          status:             'EXPIRED',
          vehicleNo:          'NW GH 7890',
          make:               'BAJAJ',
          model:              'THREE WHEELER',
          engineNo:           'DZ1234NW',
          chassisNo:          'MD27890BJAJ',
          seatingCapacity:    3,
          issuingBranch:      'Kurunegala',
          agentName:          'Direct',
        },
        revenueLicense: {
          licenseNo:        'REV-2022-NWGH7890',
          issueDate:        new Date('2022-01-01'),
          expiryDate:       new Date('2022-12-31'),   // EXPIRED
          issuingAuthority: 'North Western Province Revenue',
          annualFee:        1500.00,
          status:           'EXPIRED',
        },
      },
    ],
  },
];

module.exports = mockDrivers;
